### ISSUE TITLE
error searching for "perl" in aggregated feed

### ISSUE THREAD

**Issue by mangtronix** [internetarchive/bookserver#13]
http://bookserver.archive.org/aggregator/opensearch?q=perl&start=0

Returns:
internal server error

Error log:
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212] Traceback (most recent call last):
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]   File "/petabox/sw/lib/python/web/application.py", line 242, in process
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]     return self.handle()
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]   File "/petabox/sw/lib/python/web/application.py", line 233, in handle
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]     return self._delegate(fn, self.fvars, args)
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]   File "/petabox/sw/lib/python/web/application.py", line 412, in _delegate
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]     return handle_class(cls)
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]   File "/petabox/sw/lib/python/web/application.py", line 387, in handle_class
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]     return tocall(*args)
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]   File "/petabox/www/bookserver/aggregator/opds.py", line 537, in GET
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]     createOpdsEntryBook(opds, item)
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]   File "/petabox/www/bookserver/aggregator/opds.py", line 130, in createOpdsEntryBook
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]     urn = item['urn']
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212] KeyError: 'urn'
    [Tue Oct 13 23:31:39 2009] [error] [client 66.92.48.212]

**Comment by mangtronix** [comment]
Looks like urn is missing in solr results
